service: unifi-stock-checker
frameworkVersion: '3'
provider:
  name: aws
  runtime: nodejs18.x
  environment: 
    WEBHOOK: ${ssm:/unifi-stock-checker/webhook}  # fetch from SSM
    PRODUCT_SLUG: "pro/category/all-cameras-nvrs/products/uvc-g4-doorbell-pro"
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "sns:Publish"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "ssm:GetParameter"
      Resource: "arn:aws:ssm:us-east-1:485585223748:parameter/unifi-stock-checker/webhook"
functions:
  checkStock:
    handler: index.checkStock
    memorySize: 256
    events:
      - schedule: rate(15 minutes)
plugins:
  - serverless-offline
